### ISSUE TITLE
"error: uncaughtException: Cannot read property 'broadcast_address' of undefined" in NSQJS v0.8 (v0.8.3)

### ISSUE THREAD

**Issue by dazwin** [dudleycarr/nsqjs#142]
Beginning v0.8.3 I get this message after instantiating an nsq.Reader(). Here's the full stack:
```
error: uncaughtException: Cannot read property 'broadcast_address' of undefined date=Wed Jun 21 2017 18:37:25 GMT+0000 (UTC), pid=30292, uid=1000, gid=1000, cwd=/vagrant/myproj, execPath=/usr/bin/nodejs, version=v6.11.0, argv=[/usr/bin/nodejs, /vagrant/myproj/worker.js], rss=70451200, heapTotal=67293184, heapUsed=34500424, external=18141374, loadavg=[0.7880859375, 0.5654296875, 0.32373046875], uptime=12279
TypeError: Cannot read property 'broadcast_address' of undefined
    at /vagrant/myproj/node_modules/nsqjs/lib/lookupd.js:62:16
    at /vagrant/myproj/node_modules/nsqjs/node_modules/underscore/underscore.js:341:28
    at Array.forEach (native)
    at _.each._.forEach (/vagrant/myproj/node_modules/nsqjs/node_modules/underscore/underscore.js:79:11)
    at Function.indexBy (/vagrant/myproj/node_modules/nsqjs/node_modules/underscore/underscore.js:340:7)
    at _.(anonymous function) [as indexBy] (/vagrant/myproj/node_modules/nsqjs/node_modules/underscore/underscore.js:1123:39)
    at dedupeOnHostPort (/vagrant/myproj/node_modules/nsqjs/lib/lookupd.js:61:37)
    at /vagrant/myproj/node_modules/nsqjs/lib/lookupd.js:84:29
    at /vagrant/myproj/node_modules/nsqjs/node_modules/async/dist/async.js:1074:9
    at /vagrant/myproj/node_modules/nsqjs/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/vagrant/myproj/node_modules/nsqjs/node_modules/async/dist/async.js:998:13)
    at /vagrant/myproj/node_modules/nsqjs/node_modules/async/dist/async.js:906:16
    at /vagrant/myproj/node_modules/nsqjs/node_modules/async/dist/async.js:1071:13
    at Request._callback (/vagrant/myproj/node_modules/nsqjs/lib/lookupd.js:47:12)
    at Request.self.callback (/vagrant/myproj/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
```

v0.7.13 works Ok. I'm unable to test v0.8.0 through v0.8.2 because of a version incompatibility.

Running Node v6.11.0

**Comment by dudleycarr** [comment]
Fixed in #152
