### ISSUE TITLE
How to `fix  failed ID not in flight`?

### ISSUE THREAD

**Issue by IzaGz** [dudleycarr/nsqjs#226]
I have the Touch enabled.
`
Touch [09b12152cc8c2000]
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: E_TOUCH_FAILED TOUCH 09b12152cc8c2000 failed ID not in flight
    at NSQDConnection.receiveData (/nsqjs/node_modules/nsqjs/lib/nsqdconnection.js:302:43)
    at NSQDConnection.receiveRawData (/nsqjs/node_modules/nsqjs/lib/nsqdconnection.js:274:37)
    at Socket.conn.on.data (/nsqjs/node_modules/nsqjs/lib/nsqdconnection.js:184:34)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
Emitted 'error' event at:
    at NSQDConnection.conn.on.err (/nsqjs/node_modules/nsqjs/lib/reader.js:206:12)
    at NSQDConnection.emit (events.js:185:15)
    at ConnectionState.Enter (/nsqjs/node_modules/nsqjs/lib/nsqdconnection.js:723:17)
    at EventEmitter.emit (events.js:180:13)
    at callback (/nsqjs/node_modules/node-state/lib/nodestate.js:84:32)
    at ConnectionState.ERROR (/nsqjs/node_modules/nsqjs/lib/nsqdconnection.js:786:14)
    at ConnectionState.NodeState.goto (/nsqjs/node_modules/node-state/lib/nodestate.js:90:16)
    at NSQDConnection.receiveData (/nsqjs/node_modules/nsqjs/lib/nsqdconnection.js:302:29)
    at NSQDConnection.receiveRawData (/nsqjs/node_modules/nsqjs/lib/nsqdconnection.js:274:37)
    [... lines matching original stack trace ...]
    at TCP.onread (net.js:581:20)
`
maybe i should try starting with biggest nsqd `--max-msg-timeout=` parameter? nsq documentation says it default to  (default 15m0s).
I still dont understand which times are expired.

**Comment by dudleycarr** [comment]
It's really hard to say without seeing a reproducible example.

**Comment by emaincourt** [comment]
@IzaGz if it might help you, you actually need to tune `--max-msg-timeout` to ensure you will always be able to `TOUCH` the message. Moreover, you can check the `hasResponded` field of your message. If you don't care, you can also define a high value for both `--max-msg-timeout` and `--msg-timeout` but it might cause some issues if you consuming instances would die.
