### ISSUE TITLE
 if start nsqjs ( nsq  runnig locally)  Error: getaddrinfo ENOTFOUND s-MacBook-Air.local s-MacBook-Air.local:4150     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

### ISSUE THREAD

**Issue by triesa** [dudleycarr/nsqjs#248]
macOs Mojave if i have running docker for mac and starting nodejs with nsqjs i got.

```      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND s-MacBook-Air.local s-MacBook-Air.local:4150
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
Emitted 'error' event at:
    at NSQDConnection.conn.on.err (/Users/z/project/node_modules/nsqjs/lib/reader.js:207:12)
    at NSQDConnection.emit (events.js:185:15)
    at ConnectionState.Enter (/Users/z/project/node_modules/nsqjs/lib/nsqdconnection.js:723:17)
    at EventEmitter.emit (events.js:180:13)
    at callback (/Users/z/project/node_modules/node-state/lib/nodestate.js:84:32)
    at ConnectionState.ERROR (/Users/z/project/node_modules/nsqjs/lib/nsqdconnection.js:786:14)
    at ConnectionState.NodeState.goto (/Users/z/project/node_modules/node-state/lib/nodestate.js:90:16)
    at Socket.conn.on.err (/Users/z/project/node_modules/nsqjs/lib/nsqdconnection.js:189:25)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

nsq running locally

**Comment by triesa** [comment]
seems related https://github.com/nodejs/node/issues/5436

**Comment by dudleycarr** [comment]
Make sure that `s-MacBook-Air.local` actually resolves for you. If it doesn't then, you need to specify the broadcast address that nsqd uses to advertise itself to lookupd.

**Comment by triesa** [comment]
@dudleycarr   you mean i should check the s-MacBook-Air.local -  ping?
