### ISSUE TITLE
My local PC nsqjs reader fails with nsq on remote server

### ISSUE THREAD

**Issue by katemicse** [dudleycarr/nsqjs#255]
Hello!

I have NSQ docker-compose on remote server.

And i want to run nsqjs readers on my local PC. 

The reader config:
```
const reader = new nsq.Reader('topice', 'topice_channel', {
  lookupdHTTPAddresses: '${remote_server_ip}:4161',
});
```
When i starting this, i got error?
```

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:4150
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
Emitted 'error' event at:
    at NSQDConnection.conn.on.err (/Users/kate/project/node_modules/nsqjs/lib/reader.js:207:12)
    at NSQDConnection.emit (events.js:185:15)
    at ConnectionState.Enter (/Users/kate/project/node_modules/nsqjs/lib/nsqdconnection.js:723:17)
    at EventEmitter.emit (events.js:180:13)
    at callback (/Users/kate/project/node_modules/node-state/lib/nodestate.js:84:32)
    at ConnectionState.ERROR (/Users/kate/project/node_modules/nsqjs/lib/nsqdconnection.js:786:14)
    at ConnectionState.NodeState.goto (/Users/kate/project/node_modules/node-state/lib/nodestate.js:90:16)
    at Socket.conn.on.err (/Users/kate/project/node_modules/nsqjs/lib/nsqdconnection.js:189:25)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

Maybe i do not need to use nsqlookupd on remote? How can i understand that i need the nsqlookupd, or multiply nsqlookupds, or nsqds?

**Comment by dudleycarr** [comment]
You need to specify the broadcast address on the nsqd to be the address the client needs to connect to. That value will be passed to the client via lookupd.
