### ISSUE TITLE
deferPublish

### ISSUE THREAD

**Issue by nanom1t** [dudleycarr/nsqjs#261]
Hi @dudleycarr,

I have a question about deferPublish method for NSQ. I want to use it for planned jobs at some time. 

I have a cron script (scheduler) which runs every 12 hours and creates tasks which should be runned at specific time (for example, 12:43, 14:12, etc). I can manually calculate the delay in milliseconds and publish deferred message for NSQ. The delay for messages maybe up to 12 hours.

Is it make a sense to use deferPublish method for this purpose? Is there may be some messages lost or other problems?

Thanks

**Comment by nanom1t** [comment]
It looks like there is a limitation for timeout 3600000 milliseconds or 1 hour.
```
Error: E_INVALID DPUB timeout 26821000 out of range 0-3600000
    at WriterNSQDConnection.receiveData (/vagrant/node_modules/nsqjs/lib/nsqdconnection.js:304:43)
    at WriterNSQDConnection.receiveRawData (/vagrant/node_modules/nsqjs/lib/nsqdconnection.js:276:37)
    at Socket.conn.on.data (/vagrant/node_modules/nsqjs/lib/nsqdconnection.js:186:34)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by dudleycarr** [comment]
I don't think the defer publish functionality is a good fit for your use case. Obviously, the delay max is a barrier. However, nsq doesn't give you any insight into what deferred messages you currently have published. That would at the very least be necessary if you wanted to think about having an alternative to something to cron like system.
