### ISSUE TITLE
Error: Cannot find module 'nsqjs'

### ISSUE THREAD

**Issue by ghafran** [dudleycarr/nsqjs#67]
The latest version gives the following error on 0.10.x of node.

```
npm install nsqjs
echo "var nsq = require('nsqjs');" >> test.js
node test.js
```

Give he following result:
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'nsqjs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by ghafran** [comment]
Here is the result of the npm install:
```
sudo npm install nsqjs
```
Here was the result of ```npm install nsqjs```
```
> snappy@3.0.8 install /srv/sso/node_modules/nsqjs/node_modules/snappystream/node_modules/snappy
> node-gyp rebuild

make: Entering directory `/srv/sso/node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/build'
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  SOLINK_MODULE(target) Release/obj.target/binding.node: Finished
  COPY Release/binding.node
make: Leaving directory `/srv/sso/node_modules/nsqjs/node_modules/snappystream/node_modules/snappy/build'

> sse4_crc32@2.1.2 install /srv/sso/node_modules/nsqjs/node_modules/snappystream/node_modules/sse4_crc32
> node-gyp rebuild

make: Entering directory `/srv/sso/node_modules/nsqjs/node_modules/snappystream/node_modules/sse4_crc32/build'
  CXX(target) Release/obj.target/sse4_crc32/src/sse4_crc32.o
  CC(target) Release/obj.target/sse4_crc32/src/crc32c.o
  SOLINK_MODULE(target) Release/obj.target/sse4_crc32.node
  SOLINK_MODULE(target) Release/obj.target/sse4_crc32.node: Finished
  COPY Release/sse4_crc32.node
make: Leaving directory `/srv/sso/node_modules/nsqjs/node_modules/snappystream/node_modules/sse4_crc32/build'
nsqjs@0.7.3 node_modules/nsqjs
├── node-int64@0.3.3
├── node-state@1.4.1
├── underscore@1.5.2
├── async@0.9.0
├── request@2.30.0 (json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, qs@0.6.6, tunnel-agent@0.3.0, oauth-sign@0.3.0, mime@1.2.11, node-uuid@1.4.3, form-data@0.1.4, http-signature@0.10.1, tough-cookie@0.9.15, hawk@1.0.0)
├── moment@2.4.0
├── bignumber.js@1.2.1
└── snappystream@0.3.1 (int24@0.0.1, coffee-script@1.9.1, snappy@3.0.8, sse4_crc32@2.1.2)
```

**Comment by ghafran** [comment]
I just verified that this only happens on 0.7.3.

This works:
```
npm install nsqjs@0.7.2
```

**Comment by dudleycarr** [comment]
Shoot! The lib directory wasn't built for some reason during the last push.
Will get a fix out Ina. Couple of hours!

**Comment by dudleycarr** [comment]
**Fixed!** Turns out that npm looks at `.gitignore` if you don't have a `.npmignore` file which caused the `lib` directory to be excluded.
