### ISSUE TITLE
how to increase the message size ?

### ISSUE THREAD

**Issue by thomasmodeneis** [dudleycarr/nsqjs#71]
Hi, when performing a little test with big messages I got into this.

Is there any way to set the message limit using nsqjs? 
Thank you.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: E_BAD_MESSAGE PUB message too big 1033891 > 1024768
    at WriterNSQDConnection.NSQDConnection.receiveData (/opt/g7/runner/node_modules/nsqjs/lib/nsqdconnection.js:234:57)
    at WriterNSQDConnection.NSQDConnection.receiveRawData (/opt/g7/runner/node_modules/nsqjs/lib/nsqdconnection.js:210:19)
    at Socket.<anonymous> (/opt/nsqjstest/node_modules/nsqjs/lib/nsqdconnection.js:147:20)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)

```

**Comment by dudleycarr** [comment]
This is tuned as a paramter to `nsqd` using `--max-msg-size` Check it out here:
http://nsq.io/components/nsqd.html
