### ISSUE TITLE
failed ID not in flight

### ISSUE THREAD

**Issue by thomasmodeneis** [dudleycarr/nsqjs#72]
Hi,

I'm getting this error quite often, I'm not sure why, does anyone can give me a tip of what may be wrong?

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: E_FIN_FAILED FIN 0851484049e01000 failed ID not in flight
    at NSQDConnection.receiveData (/opt/test/node_modules/nsqjs/lib/nsqdconnection.js:234:57)
    at NSQDConnection.receiveRawData (/opt/test/node_modules/nsqjs/lib/nsqdconnection.js:210:19)
    at Socket.<anonymous> (/opt/test/node_modules/nsqjs/lib/nsqdconnection.js:147:20)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
```

**Comment by mreiferson** [comment]
@thomasmodeneis this means your consumer failed to respond in time and the source `nsqd` handed the message out to another consumer, which then proceeded to `FIN` the message.

Basically, the consumer throwing the error no longer owns or can respond to the message.

**Comment by thomasmodeneis** [comment]
oh thats what I was thinking, I'm going to implement the touch, I think this will solve the problem.

Thanks for the help @mreiferson :)

Thomas
